"""add_system_log_table

Revision ID: 6eae4818974c
Revises: a2296c1316c1
Create Date: 2026-07-24 09:24:16.409222
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6eae4818974c'
down_revision: Union[str, None] = 'a2296c1316c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_system_log',
    sa.Column('level', sa.String(length=16), nullable=False, comment='日志级别: INFO/WARNING/ERROR/DEBUG'),
    sa.Column('module', sa.String(length=64), nullable=False, comment='模块名称: risk/workflow/contract/approval/system'),
    sa.Column('message', sa.Text(), nullable=False, comment='日志消息'),
    sa.Column('detail', sa.Text(), nullable=True, comment='详细信息（JSON 格式）'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='雪花 ID 主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_system_log_level'), 't_system_log', ['level'], unique=False)
    op.create_index(op.f('ix_t_system_log_module'), 't_system_log', ['module'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_system_log_module'), table_name='t_system_log')
    op.drop_index(op.f('ix_t_system_log_level'), table_name='t_system_log')
    op.drop_table('t_system_log')
    # ### end Alembic commands ###