"""init

Revision ID: a2296c1316c1
Revises: 
Create Date: 2026-07-23 20:23:51.359557
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a2296c1316c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_approval_comment',
    sa.Column('comment_id', sa.String(length=128), nullable=False, comment='评论业务 ID(幂等键)'),
    sa.Column('approval_order_id', sa.BigInteger(), nullable=False, comment='关联审批单 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('risk_level', sa.String(length=32), nullable=True, comment='综合风险等级'),
    sa.Column('risk_summary', sa.Text(), nullable=True, comment='风险摘要'),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False, comment='是否 AI 生成'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='雪花 ID 主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_approval_comment_approval_order_id'), 't_approval_comment', ['approval_order_id'], unique=False)
    op.create_index(op.f('ix_t_approval_comment_comment_id'), 't_approval_comment', ['comment_id'], unique=True)
    op.create_table('t_approval_order',
    sa.Column('approval_id', sa.String(length=64), nullable=False, comment='OA 审批单 ID'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='审批单标题'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='审批状态: pending/approved/rejected/cancelled'),
    sa.Column('applicant', sa.String(length=100), nullable=False, comment='申请人'),
    sa.Column('department', sa.String(length=200), nullable=False, comment='申请部门'),
    sa.Column('oa_created_at', sa.DateTime(), nullable=True, comment='OA 系统创建时间'),
    sa.Column('raw_data', sa.Text(), nullable=True, comment='原始 JSON 数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='雪花 ID 主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_approval_order_approval_id'), 't_approval_order', ['approval_id'], unique=True)
    op.create_index(op.f('ix_t_approval_order_status'), 't_approval_order', ['status'], unique=False)
    op.create_table('t_contract_document',
    sa.Column('doc_id', sa.String(length=64), nullable=False, comment='文档业务 ID'),
    sa.Column('approval_order_id', sa.BigInteger(), nullable=False, comment='关联审批单 ID'),
    sa.Column('file_name', sa.String(length=500), nullable=False, comment='原始文件名'),
    sa.Column('file_md5', sa.String(length=64), nullable=False, comment='文件 MD5 值'),
    sa.Column('minio_path', sa.String(length=500), nullable=False, comment='MinIO 存储路径'),
    sa.Column('file_type', sa.String(length=32), nullable=False, comment='文件类型: pdf/word/image'),
    sa.Column('is_scanned', sa.Boolean(), nullable=False, comment='是否为扫描件'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小(字节)'),
    sa.Column('parse_status', sa.String(length=32), nullable=False, comment='解析状态: pending/parsing/parsed/failed'),
    sa.Column('parse_text', sa.Text(), nullable=True, comment='解析出来的文本内容'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='雪花 ID 主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_contract_document_approval_order_id'), 't_contract_document', ['approval_order_id'], unique=False)
    op.create_index(op.f('ix_t_contract_document_doc_id'), 't_contract_document', ['doc_id'], unique=True)
    op.create_index(op.f('ix_t_contract_document_file_md5'), 't_contract_document', ['file_md5'], unique=False)
    op.create_index(op.f('ix_t_contract_document_parse_status'), 't_contract_document', ['parse_status'], unique=False)
    op.create_table('t_contract_field',
    sa.Column('document_id', sa.BigInteger(), nullable=False, comment='关联文档 ID'),
    sa.Column('contract_no', sa.String(length=128), nullable=True, comment='合同编号'),
    sa.Column('party_a_info', sa.Text(), nullable=True, comment='甲方信息(JSON)'),
    sa.Column('party_b_info', sa.Text(), nullable=True, comment='乙方信息(JSON)'),
    sa.Column('amount', sa.String(length=64), nullable=True, comment='合同金额'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='合同开始日期'),
    sa.Column('end_date', sa.DateTime(), nullable=True, comment='合同结束日期'),
    sa.Column('payment_terms', sa.Text(), nullable=True, comment='付款条款'),
    sa.Column('liability_clause', sa.Text(), nullable=True, comment='违约责任'),
    sa.Column('confidentiality', sa.Text(), nullable=True, comment='保密条款'),
    sa.Column('dispute_resolution', sa.Text(), nullable=True, comment='争议解决方式'),
    sa.Column('raw_fields_json', sa.Text(), nullable=True, comment='原始字段 JSON(LLM 输出)'),
    sa.Column('extract_confidence', sa.Float(), nullable=True, comment='提取置信度 0-1'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='雪花 ID 主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_contract_field_document_id'), 't_contract_field', ['document_id'], unique=True)
    op.create_table('t_risk_review_result',
    sa.Column('risk_id', sa.String(length=64), nullable=False, comment='风险结果业务 ID'),
    sa.Column('approval_order_id', sa.BigInteger(), nullable=False, comment='关联审批单 ID'),
    sa.Column('rule_id', sa.BigInteger(), nullable=True, comment='关联规则 ID'),
    sa.Column('risk_level', sa.String(length=32), nullable=False, comment='风险等级: HIGH/MEDIUM/LOW'),
    sa.Column('risk_description', sa.Text(), nullable=False, comment='风险描述'),
    sa.Column('suggestion', sa.Text(), nullable=True, comment='修改建议'),
    sa.Column('source_text', sa.Text(), nullable=True, comment='原文引用'),
    sa.Column('field_name', sa.String(length=64), nullable=True, comment='关联字段名'),
    sa.Column('is_valid', sa.Boolean(), nullable=False, comment='是否有效(人工确认)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='雪花 ID 主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_risk_review_result_approval_order_id'), 't_risk_review_result', ['approval_order_id'], unique=False)
    op.create_index(op.f('ix_t_risk_review_result_risk_id'), 't_risk_review_result', ['risk_id'], unique=True)
    op.create_index(op.f('ix_t_risk_review_result_rule_id'), 't_risk_review_result', ['rule_id'], unique=False)
    op.create_table('t_risk_rule',
    sa.Column('rule_code', sa.String(length=64), nullable=False, comment='规则编码'),
    sa.Column('rule_name', sa.String(length=200), nullable=False, comment='规则名称'),
    sa.Column('rule_category', sa.String(length=64), nullable=False, comment='规则分类: amount/term/clause/subject/compliance'),
    sa.Column('rule_type', sa.String(length=32), nullable=False, comment='规则类型: field/llm/composite'),
    sa.Column('rule_config_json', sa.Text(), nullable=True, comment='规则配置 JSON'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级'),
    sa.Column('risk_level', sa.String(length=32), nullable=False, comment='风险等级: HIGH/MEDIUM/LOW'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('description', sa.Text(), nullable=True, comment='规则描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='雪花 ID 主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_index(op.f('ix_t_risk_rule_is_enabled'), 't_risk_rule', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_t_risk_rule_rule_category'), 't_risk_rule', ['rule_category'], unique=False)
    op.create_table('t_system_config',
    sa.Column('config_key', sa.String(length=128), nullable=False, comment='配置键'),
    sa.Column('config_value', sa.Text(), nullable=False, comment='配置值'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='配置说明'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='雪花 ID 主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key')
    )
    op.create_table('t_task_retry_log',
    sa.Column('task_id', sa.BigInteger(), nullable=False, comment='关联任务 ID'),
    sa.Column('node_name', sa.String(length=64), nullable=False, comment='节点名称'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='第几次重试'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('error_type', sa.String(length=64), nullable=True, comment='错误类型'),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True, comment='下次重试时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='雪花 ID 主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_task_retry_log_task_id'), 't_task_retry_log', ['task_id'], unique=False)
    op.create_table('t_workflow_task',
    sa.Column('task_id', sa.String(length=64), nullable=False, comment='任务业务 ID'),
    sa.Column('approval_order_id', sa.BigInteger(), nullable=False, comment='关联审批单 ID'),
    sa.Column('workflow_name', sa.String(length=128), nullable=False, comment='工作流名称'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='任务状态: pending/running/success/failed/blocked'),
    sa.Column('current_node', sa.String(length=64), nullable=True, comment='当前执行节点'),
    sa.Column('state_json', sa.Text(), nullable=True, comment='状态快照 JSON'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='已重试次数'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True, comment='耗时(毫秒)'),
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False, comment='雪花 ID 主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_workflow_task_approval_order_id'), 't_workflow_task', ['approval_order_id'], unique=False)
    op.create_index(op.f('ix_t_workflow_task_status'), 't_workflow_task', ['status'], unique=False)
    op.create_index(op.f('ix_t_workflow_task_task_id'), 't_workflow_task', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_workflow_task_task_id'), table_name='t_workflow_task')
    op.drop_index(op.f('ix_t_workflow_task_status'), table_name='t_workflow_task')
    op.drop_index(op.f('ix_t_workflow_task_approval_order_id'), table_name='t_workflow_task')
    op.drop_table('t_workflow_task')
    op.drop_index(op.f('ix_t_task_retry_log_task_id'), table_name='t_task_retry_log')
    op.drop_table('t_task_retry_log')
    op.drop_table('t_system_config')
    op.drop_index(op.f('ix_t_risk_rule_rule_category'), table_name='t_risk_rule')
    op.drop_index(op.f('ix_t_risk_rule_is_enabled'), table_name='t_risk_rule')
    op.drop_table('t_risk_rule')
    op.drop_index(op.f('ix_t_risk_review_result_rule_id'), table_name='t_risk_review_result')
    op.drop_index(op.f('ix_t_risk_review_result_risk_id'), table_name='t_risk_review_result')
    op.drop_index(op.f('ix_t_risk_review_result_approval_order_id'), table_name='t_risk_review_result')
    op.drop_table('t_risk_review_result')
    op.drop_index(op.f('ix_t_contract_field_document_id'), table_name='t_contract_field')
    op.drop_table('t_contract_field')
    op.drop_index(op.f('ix_t_contract_document_parse_status'), table_name='t_contract_document')
    op.drop_index(op.f('ix_t_contract_document_file_md5'), table_name='t_contract_document')
    op.drop_index(op.f('ix_t_contract_document_doc_id'), table_name='t_contract_document')
    op.drop_index(op.f('ix_t_contract_document_approval_order_id'), table_name='t_contract_document')
    op.drop_table('t_contract_document')
    op.drop_index(op.f('ix_t_approval_order_status'), table_name='t_approval_order')
    op.drop_index(op.f('ix_t_approval_order_approval_id'), table_name='t_approval_order')
    op.drop_table('t_approval_order')
    op.drop_index(op.f('ix_t_approval_comment_comment_id'), table_name='t_approval_comment')
    op.drop_index(op.f('ix_t_approval_comment_approval_order_id'), table_name='t_approval_comment')
    op.drop_table('t_approval_comment')
    # ### end Alembic commands ###